/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hu.mosomate.twitcheventhub.ui;

import hu.mosomate.twitcheventhub.AppConstants;
import java.awt.Color;

/**
 * Modal dialog layout for adding OAuth scopes.
 * 
 * @author mosomate
 */
public class AddScopePanel extends javax.swing.JPanel {

    /**
     * When the Add button is pressed, this callback is invoked
     */
    private final ModalDialogCallback callback;
    
    /**
     * Creates new form AddScopePanel
     * 
     * @param callback 
     */
    public AddScopePanel(ModalDialogCallback callback) {
        this.callback = callback;
        
        // Set initial state for UI components
        initComponents();
        updateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePanel = new javax.swing.JPanel();
        namePanelLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        actionButtonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();

        namePanelLabel.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        namePanelLabel.setText("Name");

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(namePanelLayout.createSequentialGroup()
                        .addComponent(namePanelLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nameField))
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namePanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionButtonPanelLayout = new javax.swing.GroupLayout(actionButtonPanel);
        actionButtonPanel.setLayout(actionButtonPanelLayout);
        actionButtonPanelLayout.setHorizontalGroup(
            actionButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionButtonPanelLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );
        actionButtonPanelLayout.setVerticalGroup(
            actionButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actionButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyReleased
        updateComponents();
    }//GEN-LAST:event_nameFieldKeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (callback == null) {
            return;
        }

        // Pass new scope to callback
        callback.onPositiveButtonClicked(nameField.getText().trim());
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateComponents() {
        // Necessary variables
        var nameFieldText = nameField.getText().trim();
        var nameFieldTextValid = nameFieldText.matches(AppConstants.OAUTH_SCOPE_REGEX);
        
        // Tint text of name field based on it's content
        if (nameFieldTextValid) {
            nameField.setForeground(new Color(204, 204, 204));
        }
        else {
            nameField.setForeground(new Color(255, 102, 102));
        }
        
        // Enable Add button if:
        // 1. name field text is not blank
        // 2. name field text is valid
        addButton.setEnabled(!nameFieldText.isBlank() && nameFieldTextValid);
    }
    
    public javax.swing.JButton getPositiveButton() {
        return addButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionButtonPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel namePanelLabel;
    // End of variables declaration//GEN-END:variables
}
